### ISSUE TITLE
[EIDA token]: get_stations does not work with several networks

### ISSUE THREAD

**Issue by aubercor** [EIDA/userfeedback#104]
Hello,

I noticed that the get_stations function does not work with several networks in parameters when associated to EIDA token authentication method.

Example:

```
from obspy.clients.fdsn import RoutingClient
from obspy import read, read_inventory
import obspy.clients.fdsn

rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': './eidatoken'})
client = obspy.clients.fdsn.Client("RESIF")
```

`inv=client.get_stations(network="RD,G", station="*")`

Works

`inv2=rsClient.get_stations(network="RD,G", station="*") `

does not work

whereas

`inv2=rsClient.get_stations(network="RD", station="*") 
`
works 

Is it normal?

Regards,
Coralie

**Comment by javiquinte** [comment]
Hi @aubercor 
From our experience in the last weeks/months I have the feeling that this could be an issue on the RESIF side (not sure though), so I'm contacting @jschaeff to check it.
Thanks for the feedback!

**Comment by jschaeff** [comment]
Hereafter is a complete script to reproduce the issue (providing the file `./eidatoken` is valid):

From what I understand, the RoutingClient.get_stations() with 2 networks does not work. I don't see anything in obspy documentation saying not to provide several networks. But I can't get why this would be an issue at Résif :)
Maybe we should run more tests.

```python
from obspy.clients.fdsn import RoutingClient, Client
import time


start_time = time.monotonic()
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': './eidatoken'})
print(f"Time for initiating RoutingClient: { time.monotonic() - start_time }")

client = Client("RESIF")
print(f"Time for initiating fdsn.Client: { time.monotonic() - start_time }")

print("===== FDSN Client getting RD,G ====")
try:
    inv = client.get_stations(network="RD,G", station="*")
    print(f"Time for getting RD and G stations with fdsn.Client: { time.monotonic() - start_time }")
    print(inv)
except Exception as e:
    print(e)
# Works

print("===== Routing Client getting RD,G ====")
try:
    inv2=rsClient.get_stations(network="RD,G", station="*")
    print(f"Time for getting RD and G stations with RoutingClient: { time.monotonic() - start_time }")
    print(inv2)
except Exception as e:
    print(e)
# does not work

print("===== Routing Client getting RD ====")
try:
    inv3=rsClient.get_stations(network="RD", station="*")
    print(f"Time for getting RD stations with RoutingClient: { time.monotonic() - start_time }")
    print(inv3)
except Exception as e:
    print(e)
 
print("===== Routing Client getting G ====")
try:
    inv3=rsClient.get_stations(network="G", station="*")
    print(f"Time for getting RD stations with RoutingClient: { time.monotonic() - start_time }")
    print(inv3)
except Exception as e:
    print(e)

**Comment by javiquinte** [comment]
Thanks for the tests!

I used them and run more examples and I found that this has nothing to do with the authentication or the token. The same result is observed without passing a token. The same behaviour is observed with other data centres different from RESIF.

The error comes from the Routing Service not supporting comma-separated networks (or stations, etc) in POST format. This is supported in GET format. After reviewing the FDSN specifications this should be supported and I'm opening an issue in the Routing Service repository.

**Comment by javiquinte** [comment]
Until the code is fixed, please avoid using comma-separated lists.

Thanks again @aubercor for your input.

**Comment by jschaeff** [comment]
Nice spotting @javiquinte  !

**Comment by kaestli** [comment]
Note that the routing documentation (v. 1.2) does actually not describe the support of comma-separated lists. On the network parameter, it says: "Select one network code" - the text provides wildcards, but no comma-separated lists. So the issue is actually with obspy not fully taking into account the EIDAWS/routing specification.

With FDSNWS, it is actually not so clear whether a GET request of comma-separated values (e.g. for STA) is allowed to translate in a single post line with comma-separated values for STA, or whether multiple POST file lines should be used. While (e.g. for fdsn-dataselect) table 1 says parameter values may be csv, the definition of the POST line says that
NET STA LOC CHA STARTTIME ENDTIME
are to be "repeated as many time as required".

**Comment by sheimers** [comment]
At https://www.fdsn.org/webservices/fdsnws-dataselect-1.1.pdf I read:

"Select one or more network codes.  Can be SEED network codes or data center defined codes.  Multiple codes are comma-separated."
...
"All rules for parameters apply equally whether specified using the GET or POST methods with the exception of blank location IDs, which must be specified as “--“ in the POST body due to spaces being used as the field separator."


It's really confusing fdsnws processes get and post requests differently, we had the same issue debugging the availability test.
