### ISSUE TITLE
[Federator] stationws-request returns partial output for specific station-list

### ISSUE THREAD

**Issue by flixha** [EIDA/userfeedback#105]
**Describe the problem**
I'm trying to request a list of station coordinates from the Federator, providing a comma-seperated list of stations. This generally works fine, but for some specific lists of stations, I receive only partial information, even though there should be more information available.

**To Reproduce**
Here is one example that works as expected (returns information for BER, DAG, DBG, NOR, KEV, KYTH, EDI, SOFL):
http://eida-federator.ethz.ch/fdsnws/station/1/query?station=KYTH,EDI,DAG,DBG,NOR,SOFL,KEV,BER&starttime=1970-01-01&endtime=2021-01-01&level=station&format=text

Here is one example that **does not work as expected** (returns only information for BER, even though all I added was "LTRK"):
http://eida-federator.ethz.ch/fdsnws/station/1/query?station=KYTH,EDI,DAG,DBG,NOR,SOFL,KEV,LTRK,BER&starttime=1970-01-01&endtime=2021-01-01&level=station&format=text

**Client**
Firefox / Chrome / wget

**Additional context**
2021-07-21T15:06Z

**Comment by damb** [comment]
What you observe is a mixture of the facts that:
- `eidaws-federator` implements a best-effort approach when serving responses i.e. endpoint requests which silently fail are not visible to the client (FDSNWS protocols unfortunately do not cover this. Therefore, a client request to `eidaws-federator` which could be served by `eidaws-federator` only partially is still a valid HTTP **200** response.)
- `eidaws-federator` implements a front-end cache for `fdsnws-station` metadata requests. I.e. responses successfully served to clients (i.e. both completely (from a client's perspective and with a HTTP **200** status code) are cached by the front-end cache.
- `eidaws-federator` may temporarily exclude an endpoint due to the *response code statistics*. This prevent endpoints from being overloaded.

I.e. the response you get is served in both cases from the front-end cache (currently configured TTL=12h, see: https://github.com/EIDA/eidaws-federator-deployment/blob/389f6e91ac5a61901881c12e7761ccab2137f41a/docker-compose/federator/eidaws_federator_station_config.yml#L46). It seems, that during the initial federation of the latter request i.e. http://eida-federator.ethz.ch/fdsnws/station/1/query?station=KYTH,EDI,DAG,DBG,NOR,SOFL,KEV,LTRK,BER&starttime=1970-01-01&endtime=2021-01-01&level=station&format=text endpoint requests partially failed for some reason (e.g. overload, etc.). 

As a work-around you can fool the front-end cache (if you know that the cache key is generated based on the query filter parameters) by means of e.g. requesting data using a slightly different `starttime` and/or `endtime`:

```bash
$ curl -v -o - "http://eida-federator.ethz.ch/fdsnws/station/1/query?station=KYTH,EDI,DAG,DBG,NOR,SOFL,KEV,LTRK,BER&starttime=1970-01-01T00:00:00.${RANDOM}&endtime=2021-01-01T00:00:00.${RANDOM}&level=station&format=text"
```

Currently, I do not see any better solution to the issue reported.

**Comment by flixha** [comment]
Thanks for your quick reply and the explanation!
So if I understand correctly, the unexpectedly short response from the second request was just a coincidence of the endpoints not responding at that time when I first sent the request. Now it does return the full list of stations, as expected, as 12 hours have passed.
I see that the limitations have to be in place somewhere to protect from overload, so thanks for sharing the workaround. I guess that as long as at least one piece of information is returned, the user can't get any warning or error message saying that at least one of the EIDA nodes did not respond?

**Comment by damb** [comment]
> So if I understand correctly, the unexpectedly short response from the second request was just a coincidence of the endpoints not responding at that time when I first sent the request. Now it does return the full list of stations, as expected, as 12 hours have passed.

Correct.

>  I guess that as long as at least one piece of information is returned, the user can't get any warning or error message saying that at least one of the EIDA nodes did not respond?

Also correct. At least if `eidaws-federator` is strictly implementing FDSNWS protocols. (Unfortunately, FDSNWS protocols are not ready to provide all features which would be useful in a distributed service environment. For instance, there is nothing like a dedicated response code for partial responses.)
Actually, from a technical perspective sending a different HTTP response code wouldn't be possible neither since FDSNWS is based on HTTP and `eidaws-federator` is streaming the response to clients. I.e. HTTP headers are gone already when sending the first chunk of data.

**Comment by flixha** [comment]
Ok thanks!  I see, so I guess this issue can be closed :-)
