### ISSUE TITLE
OX-IV stations [Metadata]

### ISSUE THREAD

**Issue by ajozi** [EIDA/userfeedback#108]
As we are using several stations of IV and OX networks for Q tomography, we need to have the exact high-frequency response of these instruments. The sensors seem to be Trillium-120, which have different P&Z for different
versions and generations. Unfortunately, we have found problems with the meta data, e.g., BOO and CAE show flat response, like Trillium-Compact, and BAD, BOO, CAE, MLN and PLRO have Trillium-C sensitivity but Trillium120P P&Z. 

Therefore, it would be very helpful if I could get the exact type of sensor, e.g., Trillium-120P, Trillium-120Q (which generation?!) or Horizon or serial number of the instruments. 

Here the list of stations that we need:
OX: BAD, BOO, CAE, CLUD, MLN, PLRO, VARN, ZOU2
IV: CTI, ROVR, SALO, STAL, TEOL

**Comment by petrrr** [comment]
This issue is already been looked into and related to a problem which was already discussed with the reporter, the data provider and the EIDA note via email. The reporting user apparently obtained the necessary information to move forward with updated metadata. 

From the datacentre side, however, we have not yet received the information, updated metadata or change requests which would allow to move forward with any changes. So this is still WIP.

As a preliminary summary the problem could be broken up into 3 mostly unrelated problems:

1. IV, digitizer descripion: There seems to be a rather subtle issue with the FIR filter description of one digitizer. This problem does not get detected easily with standard analysis, but seems to influence the high frequency response; We are trying to obtain updated descriptions.

1. IV, Trillium 120: The nominal response in the Inventory seems to use a description provided by the producer which is somewhat dated. Later an updated version has been published, but there is no process in place to catch this. The difference seems to towards the higher end of the spectrum and got undetected for the same reason. This requires a more consistent approach across the Inventory in order to be addressed.

1. network OX: There seem to be some inconsistencies between deployed sensors and metadata, mainly some mix-up between Trillium-120Q and Compact, regarding PAZ stage and/or gain. There also might be more than one version of nominal metadata in use for the same type of sensor; The EIDA node has contacted the data provider to obtain updated information.
