### ISSUE TITLE
[Service]

### ISSUE THREAD

**Issue by SarahL97** [EIDA/userfeedback#116]
**Error for download data**
I tried downloading Data from Orfeus. After choosing the event and stations but I could not download and an error was given. 

<img width="602" alt="Bildschirmfoto 2022-02-01 um 20 26 39" src="https://user-images.githubusercontent.com/82951449/152138992-07c22172-fec4-4d36-b5b7-c74ce067661b.png">

Thank you for the help!

**Comment by damb** [comment]
I assume you're referring to http://orfeus-eu.org/webdc3/.

Currently, there is some maintenance going on (see also #115).

If it is just about the MSEED data you could try accessing the `fdsnws-dataselect` service from ETH, directly. E.g.

```bash
$ curl -v -o data.mseed "http://eida.ethz.ch/fdsnws/dataselect/1/query?net=CH&sta=SBAT&start=2016-12-08T16:46:39&end=2016-12-08T16:53:39"
```

**Comment by SarahL97** [comment]
@damb Yes I am talking about the orfeus page. The ETH directed me to the orfeus page. But thank you for your answer.

**Comment by javiquinte** [comment]
Dear Sarah,
please try the alternative version of WebDC3 running at GEOFON. It should provide you exactly the same data and functionality.
http://eida.gfz-potsdam.de/webdc3/
And please let us know if it works as expected.
If the problem is on the end point (i.e. ETH) there should be an error message in the "View Console" tab.

**Comment by SarahL97** [comment]
Dear Javier,
thank you so much. The GFZ website worked.
