### ISSUE TITLE
SL.* waveform data not available via IRIS

### ISSUE THREAD

**Issue by tesch** [EIDA/userfeedback#13]
*Client*: ObsPy 1.1.1 FDSN Client, Python 3.7.3
*Station*: SL.*
*Auth*: none
*Date*: 2019-05-22 

The entire SL network is available via the station services of `http://www.orfeus-eu.org`, and `http://service.iris.edu`. (Almost anyway, IRIS is missing SL.LEGS, and SL.ZALS)

The dataselect service of IRIS reports "no data available" for any time window I have tried so far, though. Is this intentional? Should station metadata be distributed via multiple services, even if the corresponding waveform data isn't?

```
from obspy import UTCDateTime
from obspy.clients.fdsn import Client

network = 'SL'
station = '*'

channel = '*'
location = '*'

for url in ('http://www.orfeus-eu.org', 'http://service.iris.edu'):
    client = Client(url)

    try:
        # works for both
        inventory = client.get_stations(
            network=network,
            station=station,

            starttime=UTCDateTime('2010-01-01'),
            endtime=UTCDateTime('2019-04-30'),

            level='station')

        print(inventory)
    except:
        print('station service unavailable (', url, ')', sep='')

    try:
        # doesn't work for both
        stream = client.get_waveforms(
            network=network,
            station=station,

            channel=channel,
            location=location,

            starttime=UTCDateTime('2018-01-01 12:00:00'),
            endtime=UTCDateTime('2018-01-01 12:30:00'))

        print(stream)
    except:
        print('dataselect service unavailable (', url, ')', sep='')
```

**Comment by javiquinte** [comment]
Hi @tesch 
We (EIDA) distribute data and metadata from our networks from the authoritative data centres. From what I see, ODC is the data centre which has to distribute this. You are getting data and metadata from ODC, so I see no problem. We don't know exactly what IRIS has. And sometimes they replicate some (meta)data from us on their own, but you will never be sure whether there are inconsistencies or not.
First advice: data should be downloaded from ODC.
Second advice: check the README file on the main page of this repository. There you will find the proper way to download EIDA data with Obspy (using the RoutingClient). Give it a try and let us know.

I'll leave this issue open just in case that @Jollyfant wants to comment something. Otherwise, please close it, @Jollyfant !
