### ISSUE TITLE
[No Data] for 4C+ station

### ISSUE THREAD

**Issue by rafa0110** [EIDA/userfeedback#133]
Client: GFZ
Station time windows: 4C+ (All stations) ; time windows: starttime: 2017.10.15; endtime: 2019.12.31
Error:   HTTP code: 204

 I am using an EIDA token, which is working well because it was tested in: http://eida.gfz-potsdam.de/webdc3/. Here I can get the data for almost all the stations. There are two stations in which I cannot get data there (BAJ7 and FRK7).

My problem is when I try to get the data using client.get_waveforms(**args) (in Python) I can only get part of the data for all stations (from 2017.10.15 to beginning of January 2019), but not for the rest of the year (2019).

![Screenshot from 2022-10-02 23-03-17](https://user-images.githubusercontent.com/70123899/193476401-44e0096f-e603-4c01-a8f4-b0edcd039299.png)
![Screenshot from 2022-10-02 22-12-34](https://user-images.githubusercontent.com/70123899/193476403-fc7dfca2-0f71-4ee8-91b6-c6ca91033ad1.png)

Let me know if you need further details.
Could you give me some advice?

Many thanks in advance

**Comment by javiquinte** [comment]
Dear @rafa0110 ,

thanks for contacting us. I would appreciate more information on your requests, because it is not so clear. if I understood correctly, you report two different problems here.

We would need:

- a precise timewindow for the not working request using WebDC3
- a minimum number of lines of code with the request not working in the case of Obspy

In the meantime, please be aware that in the case of stations archived at GFZ, you have a useful webpage showing the availability of the data for different stations.

https://geofon.gfz-potsdam.de/waveform/archive/data.php

If you look there you will see that there is data for BAJ7 and FRK7 only until late 2018. You can also check the availability of other stations.

Please, send us the missing details so that we can solve your issues.

And again, thanks for reporting this.

**Comment by jschaeff** [comment]
Closing this issue. If you have more details to share, feel free to open it again.
