### ISSUE TITLE
case change in parameter string leads to Bad Request

### ISSUE THREAD

**Issue by ftilmann** [EIDA/userfeedback#173]
The federator is sensitive to the case of the parameter. Strictly speaking, I guess this is conforming to FDSN standard, but it seems petty to insist in the absence of ambiguity and individual EIDA nodes to not seem bothered. 
So the following succeeds

```
wget "https://federator.orfeus-eu.org/fdsnws/station/1/query?minlatitude=45&maxlatitude=50&minlongitude=15&maxlongitude=20&level=station&format=text" -O test.txt
```
while this fails as a bad request
```
wget "https://federator.orfeus-eu.org/fdsnws/station/1/query?Minlatitude=45&Maxlatitude=50&minlongitude=15&maxlongitude=20&level=station&format=text" -O test.txt
```
(note capital M in Minlatitude)

Of course not a big deal but can lead to some frustration due to inconsistency with other WS implementations.  I assume it would be easy to fix

**Comment by jschaeff** [comment]
Hello,

As you stated, each webservice implementation can implement more stuff than the specification, in this case, add support for case insensitive parameters.
Yet, I don't see the lack of extensions as an issue to fix.

Furthermore, there are a lot of implementations of those webservices around the world, and it's not a good thing that users get used to non-specified behaviours. Your issue is just an illustration of this.

While this seems to be a "little" thing, going this path will lead to more code and more maintainance in time. I would advise against it.

Kind regards,

**Comment by kaestli** [comment]
Ciao,
as the current implementation of the federator request parameters is in line with the FDSN specification https://www.fdsn.org/webservices/ as well as with the declared capabilities http://eida-federator.ethz.ch/fdsnws/station/1/application.wadl , we don't see an urgent need for changes.

**Comment by kaestli** [comment]
Ciao,
as the current implementation of the federator request parameters is in line with the FDSN specification https://www.fdsn.org/webservices/ as well as with the declared capabilities http://eida-federator.ethz.ch/fdsnws/station/1/application.wadl , we don't see an urgent need for changes.
