### ISSUE TITLE
[FDSNWS] net argument should allow exclusion flag

### ISSUE THREAD

**Issue by ftilmann** [EIDA/userfeedback#25]
In the IRIS implementation of the FDSNWS station , and probably other webservices, though I did not test this, it is possible to give an exclusion criterion, e.g. `... &net=-SY& ..` will return stations from all networks except SY. While ORFEUS does not have any holdings quite as horrible as SY, exclusion of a network in geography based enquiries could still be very useful, but e.g., 

```
wget -O testgeofon.txt "http://geofon.gfz-potsdam.de/fdsnws/station/1/query?minlat=-29&maxlat=-23&minlon=-72&maxlon=-68&starttime=2019-07-01&format=text&net=-SY
```
will return empty file, whereas leaving out the net argument will return a few stations. 

As I don't know whether this is an IRIS specific extension or is actually specified in the FDSN standard, I don't know whether to classify this as a bug report or feature request.

**Comment by javiquinte** [comment]
The exclusion flag is simply not supported by SeisComP3 because it is not in the standard. If you use `net=-SY` it will look for network `-SY`.
When you are doing a geographical search and also use the `net` parameter you filter the list of networks/stations by both criteria. But as the exclusion flag is not supported, the result will always be empty (Code: 204).

I will add a Feature request to the SeisComP developers.
