### ISSUE TITLE
INGV services available

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#3]
https://github.com/EIDA/userfeedback/issues/1#issuecomment-486643114

During the planned data download tests @flofuchs experienced problems several times with INGV services. 

Any hint would be appreciated. 
Thanks in advance!

**Comment by flofux** [comment]
The last couple of days (e.g. Friday 26. April or Monday 29. April) it was working fine and I think it was just temporary issues (due to the update?). I think this can be closed.

**Comment by javiquinte** [comment]
Hi INGV'ers 😉
Any comment to @flofux about the possible causes of the downtime would be much appreciated!

**Comment by massimo1962** [comment]
dear all,
firstly I'm very sorry for this very late response.
As far I understood, after a deep inquiry, this kind of problem could belong to our 'policy' about data download.
Consider that we have implemented a mechanism which manage the massive requests in this way:
only 10 (4 for dataselect) request per second per IP are allowed;
from 10 to 100 the requests are delayed;
over 100 the ws returned a 429 code (limit_req_status) ;
after 10 time that the 429 code is issued the IP will banned for three hours.
this situation could be generate, for instance, if you try to get some data that are not available, the service is very fast to reply to the client and the limits on requests number could be reached up very soon.
I pasted here a hypothetical scenario, that could really happen, in order to better explain the point.

"""
* you request data which are not available and get therefore Status 204. (in particularly in the initial phase)
* you ignore and go to the next request.
* The reply is very fast and therefore you exceed the rate limit which is currently at 4/s
* after some of these requests you get an error code 429: Too many requests.
* you ignore this as well
* you continue with these failing requests and at some point get banned.

So independently of your intention to modify your download strategy or not, you should definitely improve your error handling, e.g. wait on code 429.
"""
I hope this could be useful, please let me know.

**Comment by petrrr** [comment]
Recently we had some networking issued caused by work on the infrastructure of our institute.
We were informed by our net administrators that they expect the observed issues with DNS to be solved. 

Please provide feedback now.

From what you are writing the policy should not be an issue here, because it worked for you already. The only thing is to respect the specific feedback status code 429, and **not ignoring**. In general you will not hit the limit with valid request. Only invalid requests or run-away scripts are subject to this limit.

**Comment by javiquinte** [comment]
@petrrr The problems were reported one month before. They are not related to a *recent issue*

**Comment by massimo1962** [comment]
As far we see, also from logs, here the point is modify INGV policy for these services. I think that this is to be discuss between INGV and EIDA (ETC?; EMB?). We have to set up a meeting/telco and draw down new -shared- policy.

**Comment by javiquinte** [comment]
> As far we see, also from logs, here the point is modify INGV policy for these services. I think that this is to be discuss between INGV and EIDA (ETC?; EMB?). We have to set up a meeting/telco and draw down new -shared- policy.

Yes, you are totally right. I'll close the issue as the solution will come from this meeting.
Thanks @massimo1962 for your help!
