### ISSUE TITLE
[No Data received]

### ISSUE THREAD

**Issue by cornandhoney** [EIDA/userfeedback#41]
Dear everyone,

I am very new on using eidatoken.
I have made it about a few days ago and it could be used to download restricted data from CX network as shown in the example.
However, I got an issue when I was trying to download restricted data from IA network.
Is that still possible to download waveform data from IA using eidatoken? or do I need to follow any other steps?
Looking forward to your feedback.

As addition, I'd like to attach the following information to help you understand the issue
* Network: IA Station: APSI
* Time windows requested: 2018,01,01,22,30,00 2018,01,01,23,00,00
* Snippet of code: 

> (obspy) [retno@localhost ~]$ ./fdsnws_fetch -f req.arclink -a /home/retno/Downloads/eidatoken -v -o data.mseed

* Screenshot or copy/paste of the error: 
![Screenshot from 2019-12-12 17-56-04](https://user-images.githubusercontent.com/39262311/70698487-f4133780-1d0a-11ea-93c1-63e12c2a3066.png)

* When was this exactly done? Dec 8, 2019

Best wishes,
Retno

**Comment by javiquinte** [comment]
Dear Retno (@cornandhoney )
I would need 2 things to clarify the problem:
* your email address which you used previously to access the IA data, and
* copy/paste the part of your token with human-readable text (don't post the whole token; it's private)

Thanks!

**Comment by cornandhoney** [comment]
Dear @javiquinte,

Thank you for the reply. 

1. masyitharetno@gmail.com
2. BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2020-01-07T11:35:50.123572Z", "cn": "Masyitha Retno Kiraman", "memberof": "/epos;/", "sn": "Kiraman", "issued": "2019-12-08T11:35:50.123580Z", "mail": "masyitharetno@gmail.com", "givenName": "Masyitha Retno", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

Sincerely,
Retno

**Comment by javiquinte** [comment]
Dear Retno,
thanks for the information. Did you have access before to IA.APSI with this email account? From gmail? Could it be that you have access with another account? I've checked the list of people authorized to request data and you don't seem to be there.
Please, give me more details like: since when you have access to these data, who authorized you, when was the last time you got data from this station, etc.
Cheers,

**Comment by cornandhoney** [comment]
Dear @javiquinte,

Thank you for the reply.
Here is my answer

> 1. Did you have access before to IA.APSI with this email account? From gmail?
no, I didn't. I just made eidatoken last week by following instructions showed at the page below https://geofon.gfz-potsdam.de/waveform/arclink.php#access-to-restricted-data
and got the issue.

> 2. Could it be that you have access with another account? I've checked the list of people authorized to request data and you don't seem to be there.
I am not sure but would you please check my another email
 retno@dc.tohoku.ac.jp

> 3. When you have access to these data
I haven't downloaded any waveforms from APSI yet  

> 4. Who authorized you
do I need authorization to download the data? 

> 5. When was the last time you got data from this station.
Not yet.


Sincerely,
Retno

**Comment by javiquinte** [comment]
Dear Retno,
you are receiving an error when trying to access IA data simply because you are not allowed to do that. I'll close this issue, as there is no technical problem with the authentication/authorization process.
We will contact you via email to inform you about how to request for access permission.
Best,
