### ISSUE TITLE
[EIDA token] Grant permissions to access alparray data

### ISSUE THREAD

**Issue by fplucente** [EIDA/userfeedback#45]
Hallo, 

i would be e added to the users with permission to access Alparray data

I requested the token, but what i have received (i put its readable part in the following) doesn't give me the access to the data download.
Thanks for the help

francesco

"{"valid_until": "2020-02-21T14:48:29.187110Z", "cn": "Francesco Pio Lucente", "memberof": "/epos;/", "sn": "Lucente", "issued": "2020-01-22T14:48:29.187116Z", "mail": "pio.lucente@ingv.it", "givenName": "Francesco Pio ", "expiration": "1m"}"

**Comment by sheimers** [comment]
I have added Francesco to the alparray group.
You have to get a new token because it includes the group membership.

Stefan

**Comment by Tahiraaaa** [comment]
Hey everyone,

I also react to this issue, because unfortunately I have the same problem even if Stefan added me yesterday to the AlpArray group. After requesting today a new token.( Tried it using the Obspy example, but no success in retrieving data: I get 0 Traces in stream). I would like to know if there is sth wrong with my token?

The token has the following details:
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2020-02-07T09:32:19.161208Z", "cn": "Tahira Ashruf", "memberof": "/epos;/", "sn": "Ashruf", "issued": "2020-02-06T09:32:19.161212Z", "mail": "tahira.ashruf@ingv.it", "givenName": "Tahira", "expiration": "1d"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJeO90jAAoJEEFpzp0AlwdXK4oH/RVe/tDsIjq+SZoEDx8ealZs
FSqCeDSJRTYS5PiodcahkSY7/caTWDBTTHf+ki1G5kDsgOPog+kR2T/Ljj2b1+Wd
XUCk7KVN++oO96Pl5GQ7e8fDLPGFMgNfpTNYMOI8o8S6WhsjfTNIgXE1XRRFJeHf
HOvESvff52BAupqQ5X7zNg28x2dgmqu3YBkQoVlbHuJNhBH9LBbEVaIUYf5rZnMM
8mTI8YN7lHmQMfIkrPmA99ji6rr1BkwuUDxONQnRKwct7lsx6DhrCOlBm7w7dZP2
w8SSqzLYFqNpOj415BqHajsrubLob9CGErruaBriQiCot5Cj4omlSwoIUJwWx9g=
=+eV5
-----END PGP SIGNATURE-----

Kind regards,
Tahira

**Comment by sheimers** [comment]
Hello Tahira, I see you actually have two accounts at epos. One with the name "Tahira Ashruf" and the other one "Tahira Nicole Ashruf". Yesterday I only added the second one to the alparray group (I didn't realize there were two or the second was added later). You probably have requested the token above with your second account. I have now (2 mihnutes ago) added the second one to alparray too. Please try again.
