### ISSUE TITLE
[No Data] Routed FDSNWS requests give no data for selected Z3 stations at ETH node

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#8]
Hello again,
it seems that routed fdsnws requests for the following three stations at ETH node are not working.

Z3.A253A
Z3.A254A
Z3.A255A

I tested the years 2016, 2017, 2018. All channels are effected. Using the ObsPy routing client, no data is retrieved for those stations. Using the direct client it works fine, e.g.:

```
from obspy import UTCDateTime
from obspy.clients.fdsn import Client
from obspy.clients.fdsn import RoutingClient

direct = Client('ETH', eida_token='/home/fuchs/.eidatoken', debug=True)
routed = RoutingClient('eida-routing', credentials={'EIDA_TOKEN': '/home/fuchs/.eidatoken'}, debug=True)
```
```
direct.get_waveforms(network='Z3', station='A253A', channel='*', location='*', starttime=UTCDateTime('2017-05-01'), endtime=UTCDateTime('2017-05-02'))
```
-> 17 Trace(s) in Stream: ...

```
routed.get_waveforms(network='Z3', station='A253A', channel='*', location='*', starttime=UTCDateTime('2017-05-01'), endtime=UTCDateTime('2017-05-02'))
```
-> FDSNNoDataException: No data available for request. Detailed response of server: No content --

**Comment by javiquinte** [comment]
Yes, the problem is in the routes defined at ETH.

http://www.orfeus-eu.org/eidaws/routing/1/query?format=post&net=Z3&sta=A25*

> http://eida.ethz.ch/fdsnws/dataselect/1/query
Z3 A252A * * 2015-01-01T00:00:00 2020-07-01T00:00:00
Z3 A251A * * 2015-01-01T00:00:00 2020-07-01T00:00:00
Z3 A250A * * 2015-01-01T00:00:00 2020-07-01T00:00:00

It seems to be clear that there are 6 stations (A250A-A255A) which should be included in the routes, because ETH use them in the virtual network creation part of the Routing Service, so the other 3 are missing.

Could you fix this @sheimers ? Thanks in advance!

**Comment by sheimers** [comment]
I have updated the routes for the three missing stations on our machine today.

[http://eida.ethz.ch/eidaws/routing/1/query?format=post&net=Z3&sta=A25*](url)

It might take some time until it is propagated to the orpheus-eu.org server.

Stefan
