### ISSUE TITLE
Overlapping channel epoch for RA.SBTA.00.HN1

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#82]
See http://ws.resif.fr/fdsnws/station/1/query?net=RA&sta=SBTA&cha=HN1&level=channel&format=text

```
#Network|Station|Location|Channel|Latitude|Longitude|Elevation|Depth|Azimuth|Dip|SensorDescription|Scale|ScaleFreq|ScaleUnits|SampleRate|StartTime|EndTime
RA|SBTA|00|HN1|17.901200|-62.851700|0.0|0.0|345.0|0.0|KINEMETRICS EST|298000|1|M/S**2|125|2005-06-28T22:00:00|2009-04-20T21:00:00
RA|SBTA|00|HN1|17.901200|-62.851700|0.0|0.0|345.0|0.0|KINEMETRICS EST|298000|1|M/S**2|125|2009-04-02T22:00:00|2017-04-27T10:55:00
```

Most probably, this is simply a typo. I.e. I assume it should be `2009-04-20T22:00:00` instead of `2009-04-02T22:00:00`.

**Comment by jschaeff** [comment]
Thank you for reporting this.
@wolynied is responsible for the metadata in RA. He got a notification but is in vacation this week.

**Comment by wolynied** [comment]
Hello, 

First of all, thank you for your feedback.

This problem is solved.

We now have :
http://ws.resif.fr/fdsnws/station/1/query?net=RA&sta=SBTA&cha=HN1&level=channel&format=text

#Network|Station|Location|Channel|Latitude|Longitude|Elevation|Depth|Azimuth|Dip|SensorDescription|Scale|ScaleFreq|ScaleUnits|SampleRate|StartTime|EndTime
RA|SBTA|00|HN1|17.901200|-62.851700|0.0|0.0|345.0|0.0|KINEMETRICS EST|298000|1|m/s**2|125|2005-06-28T22:00:00|2009-04-02T21:00:00
RA|SBTA|00|HN1|17.901200|-62.851700|0.0|0.0|345.0|0.0|KINEMETRICS EST|298000|1|m/s**2|125|2009-04-02T22:00:00|2017-04-27T10:55:00

I think this problem is solved. 

Have a nice day.

David
