### ISSUE TITLE
Access from open and restricted data at the same time

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#87]
Javier,

I benefit from this issue to ask you one more thing related to Eida token.

Is it possible to access data from restricted network that required login and password when opening fdsn client?
For example:
`client = obspy.clients.fdsn.Client("RESIF", user=username, password=pwd)`

I would like to download data from mixed networks: 
- Z3 accessible with EIDA token
- open networks
- restricted networks 

I would like to open a single client which would be client from eida-routing with token as it allows to download Z3 data and data from opened networks.

Would it be possible to access data from such restricted networks?

Regards,
Coralie

_Originally posted by @aubercor in https://github.com/EIDA/userfeedback/issues/86#issuecomment-820421559_

**Comment by javiquinte** [comment]
Hi Coralie @aubercor 
When you use a `RoutingClient` from obspy you can get access to open and restricted data from the 12 data centers belonging to EIDA. All with the same command. However, you cannot mix that with requests to channels archived at IRIS.

You can use the example we provide in the README file of this repository.
https://github.com/EIDA/userfeedback#readme

I hope this answers your question.

Cheers,

**Comment by aubercor** [comment]
Hello Javier,

I did not have time to test your suggestion until now.
I did it today following your instructions but it does not work.

I would like to use these functions: 

```
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': ‘./eidatoken'}
st = rsClient.get_waveforms_bulk(bulk)

```
And to be able to download data from open and restricted networks as well.
Restricted networks can be Alparray (Z3) but also specific restricted network distributed by RESIF and accessible with username and pwd given by RESIF.

Here is my bulk:

```
bulk = [("Z3", "A183A", "00", "HHZ", starttime, endtime),
            ("Z3", "A022A", "00", "HHZ", starttime, endtime),
            ("FR", "OGAG", "00", "HHZ", starttime, endtime),
            ("XT", "CI01", "00", "HHZ", starttime, endtime)]
```

XT network is a restricted network distributed by RESIF. I got a username and pwd and to download data from it, I normally use the following :

```
client = obspy.clients.fdsn.Client("RESIF", user=username, password=pwd)
st = client.get_waveforms_bulk(bulk)
```

It works with the above code.

If I use:
```
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': ‘./eidatoken'}
st = rsClient.get_waveforms_bulk(bulk)
```

The result is: 

FR.OGAG.00.HHZ  | 2019-01-05T00:00:00.008258Z - 2019-01-05T01:59:59.998258Z | 100.0 Hz, 720000 samples
Z3.A183A.00.HHZ | 2019-01-05T00:00:00.000000Z - 2019-01-05T02:00:00.000000Z | 100.0 Hz, 720001 samples
Z3.A022A.00.HHZ | 2019-01-04T23:59:57.810000Z - 2019-01-05T02:00:03.680000Z | 100.0 Hz, 720588 samples

XT.CI01 station data is not present.

If I use:
```
client = obspy.clients.fdsn.Client("RESIF", user=username, password=pwd)
st = client.get_waveforms_bulk(bulk)
```

The result is: 

FR.OGAG.00.HHZ  | 2019-01-05T00:00:00.008258Z - 2019-01-05T01:59:59.998258Z | 100.0 Hz, 720000 samples
XT.CI01.00.HHZ  | 2019-01-05T00:00:00.000000Z - 2019-01-05T02:00:00.000000Z | 100.0 Hz, 720001 samples
Z3.A183A.00.HHZ | 2019-01-05T00:00:00.000000Z - 2019-01-05T02:00:00.000000Z | 100.0 Hz, 720001 samples

XT is present, FR as well, Z3.A181A which is a french Z3 station is present because distributed by RESIF with username and pwd as well but Z3.A022A which is not a french Z3 station is not present because only distributed through the EIDA token way.

I would like to be able to download the 4 types of stations in the above bulk with the same functions, for example:
```
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': ‘./eidatoken'}
st = rsClient.get_waveforms_bulk(bulk)
```

Do you think it may be possible?

Regards,
Coralie

**Comment by jschaeff** [comment]
I guess the 2 authentication methods (eida token or local auth) are incompatible.
With an EIDA token, the client asks the datacenter for a temporary login/password which is then used to retrieve the data.
With local authentication, the client requests directly the data with the permantent login/password.

@aubercor you need to :
- either implement this case by yourself in your program
- or ask me to register your permanent login to access also Z3 data and skip the eida_token authentication method.

**Comment by aubercor** [comment]
Hi Jonathan,

I had a doubt and It confirms to me the 2 authentication methods are incompatible.

The second solution you suggest would be the best  as I have to implement what I earlier described in a program that do not belong to me and it is really difficult to implement this case in it.

Registering my permanent login to access the whole Z3 network skipping Eida_token authentication would be the best and much easier.
Thanks,
Coralie
